// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUBppnBNLlHxtNyqykBVxvUps1YRENBOY',
    appId: '1:925585781739:web:fdf93e53aa9ef181ad1fae',
    messagingSenderId: '925585781739',
    projectId: 'sgh-project-e1afb',
    authDomain: 'sgh-project-e1afb.firebaseapp.com',
    storageBucket: 'sgh-project-e1afb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfs_i7MCtCDVHeKE99Ks04xAbGQVW17-U',
    appId: '1:925585781739:android:ee6b8db5f32322e4ad1fae',
    messagingSenderId: '925585781739',
    projectId: 'sgh-project-e1afb',
    storageBucket: 'sgh-project-e1afb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwt9DT1JBMwWOPdKT1PoUWwvcA3RoUpvY',
    appId: '1:925585781739:ios:e9f1c3189cc54f03ad1fae',
    messagingSenderId: '925585781739',
    projectId: 'sgh-project-e1afb',
    storageBucket: 'sgh-project-e1afb.appspot.com',
    iosClientId: '925585781739-o595irigte4ropsbn66hec0kl847uf2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwt9DT1JBMwWOPdKT1PoUWwvcA3RoUpvY',
    appId: '1:925585781739:ios:a1ec33752e315625ad1fae',
    messagingSenderId: '925585781739',
    projectId: 'sgh-project-e1afb',
    storageBucket: 'sgh-project-e1afb.appspot.com',
    iosClientId: '925585781739-7hp0msskdvk8a02c0vclk88us8hh8fj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject.RunnerTests',
  );
}
